package com.example.create;

import android.content.Context;
import android.content.Intent;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.recyclerview.widget.RecyclerView;

import java.util.List;

public class AdapterContact extends RecyclerView.Adapter<AdapterContact.ContactViewHolder> {

    private Context context;
    private List<ModelContact> contactList;
    private DbHelper dbHelper;


    public AdapterContact(Context context, List<ModelContact> contactList) {
        this.context = context;
        this.contactList = contactList;
        dbHelper = new DbHelper(context);
    }

    @NonNull
    @Override
    public ContactViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        View view = LayoutInflater.from(context).inflate(R.layout.row_contact_item, parent, false);
        ContactViewHolder vh = new ContactViewHolder(view);
        return vh;
    }



    @Override
    public void onBindViewHolder(@NonNull ContactViewHolder holder, int position) {
        ModelContact modelContact = contactList.get(position);
        //get data
        //we need only All data
        String id = modelContact.getId();
        String name = modelContact.getName();
        String desc = modelContact.getDescription();
        String date=modelContact.getUpdatedTime();
        String generatedId=modelContact.getAutoGeneratedId();
        holder.contactName.setText(name);
        holder.contactDesc.setText(desc);
        holder.contactDate.setText(date);
        holder.contactGeneratedId.setText(generatedId);
        holder.tvIndex.setText(String.valueOf(position + 1));

        Log.d("AdapterContact", "Binding data for position: " + position + " Name: " + name);
        holder.relativeLayout.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                // create intent to move to contactsDetails Activity with contact id as reference
                Intent intent = new Intent(context, ExperimentPageActivity.class);
                intent.putExtra("contactId", id);
                context.startActivity(intent); // now get data from details Activity
                Toast.makeText(context, "Heelo", Toast.LENGTH_SHORT).show();
            }
        });
        holder.itemView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Intent intent = new Intent(context, ExperimentPageActivity.class);
                intent.putExtra("contactId", id);
                context.startActivity(intent); // now get data from details Activity

            }
        });

    }
    @Override
    public int getItemCount() {
        return contactList.size();
    }


    class ContactViewHolder extends RecyclerView.ViewHolder {

        //view for row_contact_item
        ImageView contactDial;
        TextView contactName, contactDesc, contactDate, contactGeneratedId;
        RelativeLayout relativeLayout;
        TextView tvIndex;

        public ContactViewHolder(@NonNull View itemView) {

            super(itemView);
            tvIndex = itemView.findViewById(R.id.tv_index);
            //init view
            contactDial = itemView.findViewById(R.id.contactRv);
            contactName = itemView.findViewById(R.id.contact_name);
            contactDesc = itemView.findViewById(R.id.contact_desc);
            contactDate = itemView.findViewById(R.id.contact_date);
            contactGeneratedId = itemView.findViewById(R.id.autoGeneratedIdTextView);
            relativeLayout = itemView.findViewById(R.id.my_relative_layout);

        }

    }
}
