package com.example.create;

public class Constants {
    // database or db name
    public static final String DATABASE_NAME = "CONTACT_DB";
    //database version
    public static final int DATABASE_VERSION = 1;

    // table name
    public static final String TABLE_NAME = "CONTACT_TABLE";
    public static final String C_ID = "ID";
    public static final String C_AUTOGENERATEDID = "AUTOGENERATEDID";
    public static final String C_DESCRIPTION = "DESCRIPTION";
    public static final String C_NAME = "NAME";
    public static final String C_UPDATED_TIME = "UPDATED_TIME";


    // query for create table
    public static final String CREATE_TABLE = "CREATE TABLE " + TABLE_NAME + "( "
            + C_ID + " INTEGER PRIMARY KEY AUTOINCREMENT, "
            + C_DESCRIPTION + " TEXT, "
            + C_NAME + " TEXT, "
            + C_AUTOGENERATEDID + " TEXT, "
            + C_UPDATED_TIME + " TEXT"
            + " );";
    public static final String CREATE_EXPERIMENT_TABLE =
            "CREATE TABLE " + ExperimentContract.ExperimentEntry.TABLE_NAME + " (" +
                    ExperimentContract.ExperimentEntry._ID + " INTEGER PRIMARY KEY," +
                    ExperimentContract.ExperimentEntry.COLUMN_MODAL_ID + " INTEGER," +
                    ExperimentContract.ExperimentEntry.COLUMN_EXPERIMENT_NAME + " TEXT," +
                    "FOREIGN KEY (" + ExperimentContract.ExperimentEntry.COLUMN_MODAL_ID + ") REFERENCES " +
                    Constants.TABLE_NAME + "(" + Constants.C_ID + "))";

}