package com.example.create;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

import androidx.annotation.Nullable;

import java.util.ArrayList;

public class DbHelper extends SQLiteOpenHelper {
    public static final int DATABASE_VERSION = 3;
    public DbHelper(@Nullable Context context) {
        super(context, Constants.DATABASE_NAME, null, Constants.DATABASE_VERSION);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {

        //create table on database
        db.execSQL(Constants.CREATE_TABLE);
        db.execSQL(Constants.CREATE_EXPERIMENT_TABLE);



    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        switch (oldVersion) {
            case 1:
                // Upgrade logic from version 1 to 2 (keep your existing code if any)
                // ...
                // Fall through to include logic for the next version
            case 2:
                // Upgrade logic from version 2 to 3
                db.execSQL("ALTER TABLE " + Constants.TABLE_NAME + " ADD COLUMN new_column_name column_type");
                // If you have other upgrade logic, add it here
                break;
            default:
                throw new IllegalStateException("onUpgrade() with unknown oldVersion " + oldVersion);
        }
    }

    public long insertExperiment(String modalId, String experimentName, String experimentDescription){
        SQLiteDatabase db = this.getWritableDatabase();
        ContentValues contentValues = new ContentValues();
        contentValues.put(ExperimentContract.ExperimentEntry.COLUMN_MODAL_ID, modalId);
        contentValues.put(ExperimentContract.ExperimentEntry.COLUMN_EXPERIMENT_NAME, experimentName);
        long id = db.insert(ExperimentContract.ExperimentEntry.TABLE_NAME, null, contentValues);
        db.close();
        return id;
    }
    // Insert Function to insert data in database
    public long insertContact(String image,String name,String autoGeneratedIdTextView,String updatedTime){

        //get writable database to write data on db
        SQLiteDatabase db = this.getWritableDatabase();

        // create ContentValue class object to save data
        ContentValues contentValues = new ContentValues();

        // id will save automatically as we write query
        contentValues.put(Constants.C_DESCRIPTION,image);
        contentValues.put(Constants.C_NAME,name);
        contentValues.put(Constants.C_AUTOGENERATEDID,autoGeneratedIdTextView);
        contentValues.put(Constants.C_UPDATED_TIME,updatedTime);



        //insert data in row, It will return id of record
        long id = db.insert(Constants.TABLE_NAME,null,contentValues);

        // close db
        db.close();

        //return id
        return id;

    }

    // Update Function to update data in database
    public void updateContact(String id,String description,String name,String updatedTime, String autoGeneratedIdTextView){

        //get writable database to write data on db
        SQLiteDatabase db = this.getWritableDatabase();

        // create ContentValue class object to save data
        ContentValues contentValues = new ContentValues();

        contentValues.put(Constants.C_DESCRIPTION,description);
        contentValues.put(Constants.C_NAME,name);
        contentValues.put(Constants.C_AUTOGENERATEDID,autoGeneratedIdTextView);
        contentValues.put(Constants.C_UPDATED_TIME,updatedTime);



        //update data in row, It will return id of record
        db.update(Constants.TABLE_NAME,contentValues,Constants.C_ID+" =? ",new String[]{id} );

        // close db
        db.close();

    }

    // delete data by id
    public void deleteContact(String id){
        //get writable database
        SQLiteDatabase db =  getWritableDatabase();

        //delete query
        db.delete(Constants.TABLE_NAME,"WHERE"+" =? ",new String[]{id});

        db.close();
    }

    // delete all data
    public void deleteAllContact(){
        //get writable database
        SQLiteDatabase db = getWritableDatabase();

        //query for delete
        db.execSQL("DELETE FROM "+Constants.TABLE_NAME);
        db.close();
    }


    // get data
    public ArrayList<ModelContact> getAllData(){
        //create arrayList
        ArrayList<ModelContact> arrayList = new ArrayList<>();
        //sql command query
        String selectQuery = "SELECT * FROM "+Constants.TABLE_NAME;

        //get readable db
        SQLiteDatabase db = getReadableDatabase();
        Cursor cursor = db.rawQuery(selectQuery,null);

        // looping through all record and add to list
        if (cursor.moveToFirst()){
            do {
                ModelContact modelContact = new ModelContact(
                        // only id is integer type
                        ""+cursor.getInt(cursor.getColumnIndexOrThrow(Constants.C_ID)),
                        ""+cursor.getString(cursor.getColumnIndexOrThrow(Constants.C_DESCRIPTION)),
                        ""+cursor.getString(cursor.getColumnIndexOrThrow(Constants.C_NAME)),
                        ""+cursor.getString(cursor.getColumnIndexOrThrow(Constants.C_AUTOGENERATEDID)),
                        ""+cursor.getString(cursor.getColumnIndexOrThrow(Constants.C_UPDATED_TIME))
                );
                arrayList.add(modelContact);
            }while (cursor.moveToNext());
        }
        db.close();
        return arrayList;
    }

    // search data in sql Database
    public ArrayList<ModelContact> getSearchContact(String query){

        // it will return arraylist of modelContact class
        ArrayList<ModelContact> contactList = new ArrayList<>();

        // get readable database
        SQLiteDatabase db = getReadableDatabase();

        //query for search
        String queryToSearch = "SELECT * FROM "+Constants.TABLE_NAME+" WHERE "+Constants.C_NAME + " LIKE '%" +query+"%'";

        Cursor cursor = db.rawQuery(queryToSearch,null);

        // looping through all record and add to list
        if (cursor.moveToFirst()){
            do {
                ModelContact modelContact = new ModelContact(
                        // only id is integer type
                        ""+cursor.getInt(cursor.getColumnIndexOrThrow(Constants.C_ID)),
                        ""+cursor.getString(cursor.getColumnIndexOrThrow(Constants.C_DESCRIPTION)),
                        ""+cursor.getString(cursor.getColumnIndexOrThrow(Constants.C_NAME)),
                        ""+cursor.getString(cursor.getColumnIndexOrThrow(Constants.C_AUTOGENERATEDID)),
                        ""+cursor.getString(cursor.getColumnIndexOrThrow(Constants.C_UPDATED_TIME))

                );
                contactList.add(modelContact);
            }while (cursor.moveToNext());
        }
        db.close();
        return contactList;

    }

    public ArrayList<Experiment> getExperimentsForModal(String modalId){
        ArrayList<Experiment> experiments = new ArrayList<>();
        SQLiteDatabase db = getReadableDatabase();
        String selectQuery = "SELECT * FROM " + ExperimentContract.ExperimentEntry.TABLE_NAME +
                " WHERE " + ExperimentContract.ExperimentEntry.COLUMN_MODAL_ID + "=?";
        Cursor cursor = db.rawQuery(selectQuery, new String[]{modalId});

        if (cursor.moveToFirst()){
            do {
                Experiment experiment = new Experiment(
                        "" + cursor.getInt(cursor.getColumnIndexOrThrow(ExperimentContract.ExperimentEntry._ID)),
                        "" + cursor.getString(cursor.getColumnIndexOrThrow(ExperimentContract.ExperimentEntry.COLUMN_EXPERIMENT_NAME))
                );
                experiments.add(experiment);
            } while (cursor.moveToNext());
        }
        db.close();
        return experiments;
    }


}
